baseURL = 'https://photos.valentinriess.com/'
languageCode = 'en-us'
title = "Photostream"
theme = "photo-stream"
[params]
album_date_format = "2006"
[security.funcs]
getenv = ['^HUGO_','GITHUB_USERNAME','TWITTER_USERNAME','INSTAGRAM_USERNAME','CUSTOM_LINK_URL','CUSTOM_LINK_NAME','MASTODON_SERVER','MASTODON_USERNAME','ALLOW_ORDER_SORT_CHANGE','ALLOW_IMAGE_SHARING']